"""Add RBAC and Faculty Approval Workflow models

Revision ID: c41fa5e918dc
Revises: 
Create Date: 2026-08-13 08:32:07.333784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app
import app.database.base


# revision identifiers, used by Alembic.
revision: str = 'c41fa5e918dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', app.database.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('faculty_requests',
    sa.Column('user_id', app.database.base.GUID(length=36), nullable=False),
    sa.Column('request_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='facultyrequeststatus'), nullable=False),
    sa.Column('institution_id', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', app.database.base.GUID(length=36), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', app.database.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_requests_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_faculty_requests_user_status', ['user_id', 'status'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'DEPARTMENT_ADMIN', 'FACULTY', 'STUDENT', 'RESEARCHER', 'PARENT', 'GUEST', name='userrole'), nullable=False),
    sa.Column('permission_id', app.database.base.GUID(length=36), nullable=False),
    sa.Column('id', app.database.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role'), ['role'], unique=False)
        batch_op.create_index('ix_role_permissions_role_perm', ['role', 'permission_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'REJECTED', name='userstatus'), server_default='ACTIVE', nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('SUPER_ADMIN', 'ADMIN', 'DEPARTMENT_ADMIN', 'FACULTY', 'STUDENT', 'RESEARCHER', 'PARENT', 'GUEST', name='userrole'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'DEPARTMENT_ADMIN', 'FACULTY', 'STUDENT', 'RESEARCHER', 'PARENT', 'GUEST', name='userrole'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('status')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_role_permissions_role_perm')
        batch_op.drop_index(batch_op.f('ix_role_permissions_role'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('faculty_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_faculty_requests_user_status')
        batch_op.drop_index(batch_op.f('ix_faculty_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_requests_status'))

    op.drop_table('faculty_requests')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
