"""Core utilities, enums, and exceptions."""

from app.core.enums import (
    ActivityType,
    AssessmentDifficulty,
    AssessmentStatus,
    ConfidenceLevel,
    DifficultyLevel,
    GenerationMethod,
    LearningStyle,
    NotificationPriority,
    NotificationType,
    PredictionTrigger,
    QuestionDifficulty,
    QuestionType,
    StudyPlanStatus,
    StudyPlanType,
    TaskPriority,
    TaskStatus,
    TaskType,
    UserRole,
)
from app.core.exceptions import (
    AlreadyExistsException,
    BadRequestException,
    EduSenseException,
    ForbiddenException,
    InternalServerException,
    NotFoundException,
    UnauthorizedException,
    ValidationException,
)

__all__ = [
    "UserRole",
    "DifficultyLevel",
    "AssessmentDifficulty",
    "AssessmentStatus",
    "QuestionType",
    "QuestionDifficulty",
    "GenerationMethod",
    "LearningStyle",
    "ConfidenceLevel",
    "StudyPlanType",
    "StudyPlanStatus",
    "TaskType",
    "TaskPriority",
    "TaskStatus",
    "NotificationType",
    "NotificationPriority",
    "ActivityType",
    "PredictionTrigger",
    "EduSenseException",
    "NotFoundException",
    "AlreadyExistsException",
    "ValidationException",
    "UnauthorizedException",
    "ForbiddenException",
    "BadRequestException",
    "InternalServerException",
]
